"""Smoke tests for src/baton/protocols/soap.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_protocols_soap():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.protocols.soap")
    assert mod is not None
