"""Smoke tests for src/baton/image.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_image():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.image")
    assert mod is not None
