"""Smoke tests for src/baton/providers/gcp.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_providers_gcp():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.providers.gcp")
    assert mod is not None
