"""Smoke tests for src/baton/protocols/__init__.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_protocols___init__():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.protocols.__init__")
    assert mod is not None

def test_register_handler_is_callable():
    """Function register_handler exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.protocols.__init__")
    fn = getattr(mod, "register_handler", None)
    assert fn is not None, "'register_handler' not found in src.baton.protocols.__init__"
    assert callable(fn)

def test_get_handler_is_callable():
    """Function get_handler exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.protocols.__init__")
    fn = getattr(mod, "get_handler", None)
    assert fn is not None, "'get_handler' not found in src.baton.protocols.__init__"
    assert callable(fn)

def test_list_handlers_is_callable():
    """Function list_handlers exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.protocols.__init__")
    fn = getattr(mod, "list_handlers", None)
    assert fn is not None, "'list_handlers' not found in src.baton.protocols.__init__"
    assert callable(fn)
