"""Smoke tests for src/baton/providers/local.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_providers_local():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.providers.local")
    assert mod is not None
