"""Smoke tests for src/baton/adapter.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_adapter():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.adapter")
    assert mod is not None
