"""Smoke tests for src/baton/cli.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_cli():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.cli")
    assert mod is not None

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.cli")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in src.baton.cli"
    assert callable(fn)
