"""Smoke tests for src/baton/providers/__init__.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_providers___init__():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.providers.__init__")
    assert mod is not None

def test_create_provider_is_callable():
    """Function create_provider exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.providers.__init__")
    fn = getattr(mod, "create_provider", None)
    assert fn is not None, "'create_provider' not found in src.baton.providers.__init__"
    assert callable(fn)
