"""Smoke tests for src/baton/custodian.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_custodian():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.custodian")
    assert mod is not None
