"""Smoke tests for src/baton/protocols/protobuf.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_protocols_protobuf():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.protocols.protobuf")
    assert mod is not None
