"""Smoke tests for src/baton/signals.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_signals():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.signals")
    assert mod is not None
