"""Smoke tests for src/baton/protocols/http.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_protocols_http():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.protocols.http")
    assert mod is not None
