"""Smoke tests for src/baton/mcp_server.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_mcp_server():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    assert mod is not None

def test_resource_status_is_callable():
    """Function resource_status exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "resource_status", None)
    assert fn is not None, "'resource_status' not found in src.baton.mcp_server"
    assert callable(fn)

def test_resource_topology_is_callable():
    """Function resource_topology exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "resource_topology", None)
    assert fn is not None, "'resource_topology' not found in src.baton.mcp_server"
    assert callable(fn)

def test_resource_node_is_callable():
    """Function resource_node exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "resource_node", None)
    assert fn is not None, "'resource_node' not found in src.baton.mcp_server"
    assert callable(fn)

def test_resource_routes_is_callable():
    """Function resource_routes exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "resource_routes", None)
    assert fn is not None, "'resource_routes' not found in src.baton.mcp_server"
    assert callable(fn)

def test_resource_config_is_callable():
    """Function resource_config exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "resource_config", None)
    assert fn is not None, "'resource_config' not found in src.baton.mcp_server"
    assert callable(fn)

def test_circuit_status_is_callable():
    """Function circuit_status exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "circuit_status", None)
    assert fn is not None, "'circuit_status' not found in src.baton.mcp_server"
    assert callable(fn)

def test_list_nodes_is_callable():
    """Function list_nodes exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "list_nodes", None)
    assert fn is not None, "'list_nodes' not found in src.baton.mcp_server"
    assert callable(fn)

def test_node_detail_is_callable():
    """Function node_detail exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "node_detail", None)
    assert fn is not None, "'node_detail' not found in src.baton.mcp_server"
    assert callable(fn)

def test_show_routes_is_callable():
    """Function show_routes exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "show_routes", None)
    assert fn is not None, "'show_routes' not found in src.baton.mcp_server"
    assert callable(fn)

def test_show_metrics_is_callable():
    """Function show_metrics exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "show_metrics", None)
    assert fn is not None, "'show_metrics' not found in src.baton.mcp_server"
    assert callable(fn)

def test_show_signals_is_callable():
    """Function show_signals exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "show_signals", None)
    assert fn is not None, "'show_signals' not found in src.baton.mcp_server"
    assert callable(fn)

def test_signal_stats_is_callable():
    """Function signal_stats exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "signal_stats", None)
    assert fn is not None, "'signal_stats' not found in src.baton.mcp_server"
    assert callable(fn)

def test_show_topology_is_callable():
    """Function show_topology exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "show_topology", None)
    assert fn is not None, "'show_topology' not found in src.baton.mcp_server"
    assert callable(fn)

def test_circuit_overview_is_callable():
    """Function circuit_overview exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "circuit_overview", None)
    assert fn is not None, "'circuit_overview' not found in src.baton.mcp_server"
    assert callable(fn)

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.mcp_server")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in src.baton.mcp_server"
    assert callable(fn)
