"""Smoke tests for src/baton/tracing.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_tracing():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.tracing")
    assert mod is not None

def test_generate_trace_id_is_callable():
    """Function generate_trace_id exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.tracing")
    fn = getattr(mod, "generate_trace_id", None)
    assert fn is not None, "'generate_trace_id' not found in baton.tracing"
    assert callable(fn)

def test_generate_span_id_is_callable():
    """Function generate_span_id exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.tracing")
    fn = getattr(mod, "generate_span_id", None)
    assert fn is not None, "'generate_span_id' not found in baton.tracing"
    assert callable(fn)

def test_parse_traceparent_is_callable():
    """Function parse_traceparent exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.tracing")
    fn = getattr(mod, "parse_traceparent", None)
    assert fn is not None, "'parse_traceparent' not found in baton.tracing"
    assert callable(fn)

def test_format_traceparent_is_callable():
    """Function format_traceparent exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.tracing")
    fn = getattr(mod, "format_traceparent", None)
    assert fn is not None, "'format_traceparent' not found in baton.tracing"
    assert callable(fn)

def test_derive_telemetry_class_is_callable():
    """Function derive_telemetry_class exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.tracing")
    fn = getattr(mod, "derive_telemetry_class", None)
    assert fn is not None, "'derive_telemetry_class' not found in baton.tracing"
    assert callable(fn)

def test_resolve_telemetry_class_is_callable():
    """Function resolve_telemetry_class exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.tracing")
    fn = getattr(mod, "resolve_telemetry_class", None)
    assert fn is not None, "'resolve_telemetry_class' not found in baton.tracing"
    assert callable(fn)

def test_create_span_exporter_is_callable():
    """Function create_span_exporter exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.tracing")
    fn = getattr(mod, "create_span_exporter", None)
    assert fn is not None, "'create_span_exporter' not found in baton.tracing"
    assert callable(fn)
