"""Smoke tests for src/baton/protocols/tcp.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_protocols_tcp():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.protocols.tcp")
    assert mod is not None
