"""Smoke tests for src/baton/otel.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_otel():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.otel")
    assert mod is not None
