"""Smoke tests for src/baton/adapter_control.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_adapter_control():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.adapter_control")
    assert mod is not None
