"""Smoke tests for src/baton/dashboard_server.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_dashboard_server():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.dashboard_server")
    assert mod is not None
