"""Smoke tests for src/baton/circuit.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_circuit():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.circuit")
    assert mod is not None

def test_add_node_is_callable():
    """Function add_node exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.circuit")
    fn = getattr(mod, "add_node", None)
    assert fn is not None, "'add_node' not found in src.baton.circuit"
    assert callable(fn)

def test_remove_node_is_callable():
    """Function remove_node exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.circuit")
    fn = getattr(mod, "remove_node", None)
    assert fn is not None, "'remove_node' not found in src.baton.circuit"
    assert callable(fn)

def test_add_edge_is_callable():
    """Function add_edge exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.circuit")
    fn = getattr(mod, "add_edge", None)
    assert fn is not None, "'add_edge' not found in src.baton.circuit"
    assert callable(fn)

def test_remove_edge_is_callable():
    """Function remove_edge exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.circuit")
    fn = getattr(mod, "remove_edge", None)
    assert fn is not None, "'remove_edge' not found in src.baton.circuit"
    assert callable(fn)

def test_set_contract_is_callable():
    """Function set_contract exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.circuit")
    fn = getattr(mod, "set_contract", None)
    assert fn is not None, "'set_contract' not found in src.baton.circuit"
    assert callable(fn)

def test_has_cycle_is_callable():
    """Function has_cycle exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.circuit")
    fn = getattr(mod, "has_cycle", None)
    assert fn is not None, "'has_cycle' not found in src.baton.circuit"
    assert callable(fn)

def test_topological_sort_is_callable():
    """Function topological_sort exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.circuit")
    fn = getattr(mod, "topological_sort", None)
    assert fn is not None, "'topological_sort' not found in src.baton.circuit"
    assert callable(fn)

def test_longest_path_is_callable():
    """Function longest_path exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.circuit")
    fn = getattr(mod, "longest_path", None)
    assert fn is not None, "'longest_path' not found in src.baton.circuit"
    assert callable(fn)

def test_topology_warnings_is_callable():
    """Function topology_warnings exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.circuit")
    fn = getattr(mod, "topology_warnings", None)
    assert fn is not None, "'topology_warnings' not found in src.baton.circuit"
    assert callable(fn)
