"""Smoke tests for src/baton/collapse.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_collapse():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.collapse")
    assert mod is not None

def test_build_mock_server_is_callable():
    """Function build_mock_server exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.collapse")
    fn = getattr(mod, "build_mock_server", None)
    assert fn is not None, "'build_mock_server' not found in baton.collapse"
    assert callable(fn)

def test_compute_mock_backends_is_callable():
    """Function compute_mock_backends exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.collapse")
    fn = getattr(mod, "compute_mock_backends", None)
    assert fn is not None, "'compute_mock_backends' not found in baton.collapse"
    assert callable(fn)
