"""Smoke tests for src/baton/lifecycle.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_lifecycle():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.lifecycle")
    assert mod is not None
