"""Smoke tests for src/baton/otel.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_otel():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.otel")
    assert mod is not None
