"""Smoke tests for src/baton/federation.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_federation():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.federation")
    assert mod is not None
