"""Smoke tests for src/baton/compat.py (auto-generated by pact adopt)."""

import pytest

def test_import_src_baton_compat():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("src.baton.compat")
    assert mod is not None

def test_check_compatibility_is_callable():
    """Function check_compatibility exists and is callable."""
    import importlib
    mod = importlib.import_module("src.baton.compat")
    fn = getattr(mod, "check_compatibility", None)
    assert fn is not None, "'check_compatibility' not found in src.baton.compat"
    assert callable(fn)
