"""Smoke tests for src/baton/manifest.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_manifest():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.manifest")
    assert mod is not None

def test_load_manifest_is_callable():
    """Function load_manifest exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.manifest")
    fn = getattr(mod, "load_manifest", None)
    assert fn is not None, "'load_manifest' not found in baton.manifest"
    assert callable(fn)
