"""Smoke tests for src/baton/telemetry.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_telemetry():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.telemetry")
    assert mod is not None
