"""Smoke tests for src/baton/canary.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_canary():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.canary")
    assert mod is not None

def test_centroid_select_is_callable():
    """Function centroid_select exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.canary")
    fn = getattr(mod, "centroid_select", None)
    assert fn is not None, "'centroid_select' not found in baton.canary"
    assert callable(fn)
