"""Smoke tests for src/baton/routing.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_routing():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.routing")
    assert mod is not None

def test_ab_split_is_callable():
    """Function ab_split exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.routing")
    fn = getattr(mod, "ab_split", None)
    assert fn is not None, "'ab_split' not found in baton.routing"
    assert callable(fn)

def test_canary_is_callable():
    """Function canary exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.routing")
    fn = getattr(mod, "canary", None)
    assert fn is not None, "'canary' not found in baton.routing"
    assert callable(fn)

def test_header_route_is_callable():
    """Function header_route exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.routing")
    fn = getattr(mod, "header_route", None)
    assert fn is not None, "'header_route' not found in baton.routing"
    assert callable(fn)

def test_weighted_split_is_callable():
    """Function weighted_split exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.routing")
    fn = getattr(mod, "weighted_split", None)
    assert fn is not None, "'weighted_split' not found in baton.routing"
    assert callable(fn)
