"""Smoke tests for src/baton/schemas.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_schemas():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.schemas")
    assert mod is not None
