"""Smoke tests for src/baton/mock.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_mock():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.mock")
    assert mod is not None

def test_generate_instance_is_callable():
    """Function generate_instance exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.mock")
    fn = getattr(mod, "generate_instance", None)
    assert fn is not None, "'generate_instance' not found in baton.mock"
    assert callable(fn)

def test_parse_openapi_is_callable():
    """Function parse_openapi exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.mock")
    fn = getattr(mod, "parse_openapi", None)
    assert fn is not None, "'parse_openapi' not found in baton.mock"
    assert callable(fn)

def test_parse_json_schema_is_callable():
    """Function parse_json_schema exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.mock")
    fn = getattr(mod, "parse_json_schema", None)
    assert fn is not None, "'parse_json_schema' not found in baton.mock"
    assert callable(fn)

def test_load_routes_is_callable():
    """Function load_routes exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.mock")
    fn = getattr(mod, "load_routes", None)
    assert fn is not None, "'load_routes' not found in baton.mock"
    assert callable(fn)
