"""Smoke tests for src/baton/certs.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_certs():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.certs")
    assert mod is not None

def test_parse_certificate_is_callable():
    """Function parse_certificate exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.certs")
    fn = getattr(mod, "parse_certificate", None)
    assert fn is not None, "'parse_certificate' not found in baton.certs"
    assert callable(fn)
