"""Smoke tests for src/baton/registry.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_registry():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.registry")
    assert mod is not None

def test_load_manifests_is_callable():
    """Function load_manifests exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.registry")
    fn = getattr(mod, "load_manifests", None)
    assert fn is not None, "'load_manifests' not found in baton.registry"
    assert callable(fn)

def test_derive_circuit_is_callable():
    """Function derive_circuit exists and is callable."""
    import importlib
    mod = importlib.import_module("baton.registry")
    fn = getattr(mod, "derive_circuit", None)
    assert fn is not None, "'derive_circuit' not found in baton.registry"
    assert callable(fn)
