"""Smoke tests for src/baton/process.py (auto-generated by pact adopt)."""

import pytest

def test_import_baton_process():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("baton.process")
    assert mod is not None
